<script setup lang="ts">
type Product = { id:string; name:string; brand:string; price:number; stock:number; categoryId:string }
const props=defineProps<{product:Product}>(); const {addItem}=useCart(); const added=ref(false); let timer:ReturnType<typeof setTimeout>
const cats:Record<string,string>={'CAT-001':'โน้ตบุ๊ก','CAT-002':'เดสก์ท็อป','CAT-003':'จอมอนิเตอร์','CAT-004':'สมาร์ตโฟน','CAT-005':'แท็บเล็ต','CAT-006':'อุปกรณ์จัดเก็บข้อมูล','CAT-007':'อุปกรณ์เครือข่าย','CAT-008':'คีย์บอร์ดและเมาส์','CAT-009':'เครื่องเสียง','CAT-010':'อุปกรณ์เสริม'}
const symbols:Record<string,string>={'CAT-001':'NB','CAT-002':'PC','CAT-003':'27″','CAT-004':'5G','CAT-005':'TAB','CAT-006':'SSD','CAT-007':'WiFi','CAT-008':'⌨','CAT-009':'♪','CAT-010':'USB'}
const price=(n:number)=>new Intl.NumberFormat('th-TH').format(n)
const add=()=>{if(!props.product.stock)return;addItem(props.product.id);added.value=true;clearTimeout(timer);timer=setTimeout(()=>added.value=false,1200)};onUnmounted(()=>clearTimeout(timer))
</script>
<template><article class="card"><div class="visual" :class="`tone-${product.categoryId.slice(-1)}`"><span>{{symbols[product.categoryId]}}</span><small>{{product.brand}}</small></div><div class="body"><p>{{cats[product.categoryId]}}</p><h3>{{product.name}}</h3><div class="bottom"><div><strong>฿{{price(product.price)}}</strong><small>{{product.stock?`เหลือ ${product.stock} ชิ้น`:'สินค้าหมด'}}</small></div><button :disabled="!product.stock" :aria-label="`เพิ่ม ${product.name} ลงตะกร้า`" @click="add">{{!product.stock?'หมด':added?'✓':'+'}}</button></div></div></article></template>
<style scoped>.card{overflow:hidden;background:var(--paper);border:1px solid var(--line);border-radius:18px;transition:.25s}.card:hover{transform:translateY(-5px);box-shadow:0 16px 35px #17211b17}.visual{height:200px;padding:22px;display:flex;align-items:center;justify-content:center;position:relative;background:#dbe9df}.visual:after{content:'';width:120px;height:120px;position:absolute;border:1px solid #17211b2b;border-radius:50%}.visual span{z-index:1;font:700 2.5rem 'Space Grotesk'}.visual small{position:absolute;bottom:18px;left:20px;font-weight:700;letter-spacing:.08em}.tone-2,.tone-7{background:#f2d6be}.tone-3,.tone-8{background:#d8d5ec}.tone-4,.tone-9{background:#dce9b7}.tone-5,.tone-0{background:#f2d2ce}.body{padding:20px}.body p{margin:0 0 6px;color:var(--green);font-size:.76rem;font-weight:700}h3{min-height:48px;margin:0 0 22px;font:600 1.08rem/1.4 'Space Grotesk','IBM Plex Sans Thai'}.bottom{display:flex;justify-content:space-between;align-items:end}.bottom strong{display:block;font:700 1.18rem 'Space Grotesk'}.bottom small{display:block;margin-top:4px;color:var(--muted)}button{width:44px;height:44px;border:0;border-radius:50%;color:white;background:var(--green);font-size:1.45rem;cursor:pointer}button:disabled{background:#abb2ad;font-size:.8rem}</style>
